# Generated by Django 5.1 on 2025-02-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=100)),
                ('shoplocation', models.CharField(max_length=100)),
                ('shopcategory', models.CharField(max_length=50)),
                ('shopdescription', models.TextField(max_length=200)),
            ],
        ),
    ]
