# Generated by Django 5.1 on 2025-02-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallapp', '0002_manageoffers'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryfloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
            ],
        ),
    ]
